### PR TITLE
Dogecoin

### PR DESCRIPTION
**Pull request by SatoshiBanoshi**
DOGE-000 Official Bot

### CODE REVIEW

**Comment by Togira123** [comment]
lmao kid go outside

**Comment by GEOEGII555** [comment]
😂😂😂😂😂😂😂

**Review by GEOEGII555 — CHANGES_REQUESTED** [review]
Go brrrr a little kid who took dad's credit card to buy f*ckcoin.cc domain

**Comment by bariscodefxy** [comment]
purpose?

**Pull request closed without merging**
