### PR TITLE
fix(Commands): define command

### PR DESCRIPTION
**Pull request by jpbberry**

### CODE REVIEW

**Comment by ms5984** [comment]
Let me know if this fix is still working, I've just tested define and I haven't got a single working word so the old API does seem to have stopped working. @jpbberry , have you made an Issue for this?

**Comment by jpbberry** [comment]
> Let me know if this fix is still working, I've just tested define and I haven't got a single working word so the old API does seem to have stopped working. @jpbberry , have you made an Issue for this?

Testing in console seems to show the new package as actually returning definitions, make sure the new version is installed because the old one does not work anymore
image

The version I'm using is in the package.json of this PR

**Comment by ms5984** [comment]
@jpbberry Sorry, I might've written that in a confusing way. I tested with the *live* bot--glad to hear this fix should still work! If there's not an existing issue (about the bug your PR does in fact fix) I was hoping you could [make one](https://github.com/ChristopherBThai/Discord-OwO-Bot/issues/new/choose) :)

**Comment by jpbberry** [comment]
@ms5984 I thought it was pretty well known that the define command has just stopped working at some point. I've never been able to even use the define command to define anything for a long time. If a bug report is necessary I can make one but I think it's pretty clear that the define command doesn't work.

**Comment by ChristopherBThai** [comment]
Works! Thank you!

**Pull request merged**
