### PR TITLE
Fixed typo, when you can't trade item

### PR DESCRIPTION
**Pull request by Caviarbro**

### CODE REVIEW

**Comment by Togira123** [comment]
watch not even this getting merged :/

**Comment by ZeInhumane** [comment]
The tiniest of changes breaks prod

**Comment by bariscodefxy** [comment]
> watch not even this getting merged :/

No, there is a merged example https://github.com/ChristopherBThai/Discord-OwO-Bot/pull/267

**Comment by bariscodefxy** [comment]
> watch not even this getting merged :/

merged :)

**Pull request merged**
