### PR TITLE
Remove limited weapons

### PR DESCRIPTION
**Pull request by CleanLove2013**
Limited weapons make the imbalance in game. Not fair for newbie. Please unlimited or remove them. A Rune of the Forgotten is enough

### CODE REVIEW

**Comment by atifnimran** [comment]
Ok

**Comment by Caviarbro** [comment]
> > > Limited weapons make the imbalance in game. Not fair for newbie. Please unlimited or remove them. A Rune of the Forgotten is enough
> > 
> > 
> > The same can be said about special animals, I don't see a point why the crune should be removed.
> 
> No need remove crune, just unlimited. You can find same stats animals replace, weapons are not

Okay find me new_owo stats thank you. And the weapon is meant to be limited and I think it will be available annualy.

**Comment by CleanLove2013** [comment]
> > > > Limited weapons make the imbalance in game. Not fair for newbie. Please unlimited or remove them. A Rune of the Forgotten is enough
> > > 
> > > 
> > > The same can be said about special animals, I don't see a point why the crune should be removed.
> > 
> > 
> > No need remove crune, just unlimited. You can find same stats animals replace, weapons are not
> 
> Okay find me new_owo stats thank you. And the weapon is meant to be limited and I think it will be available annualy.

So you think new_owo is too op too? 3 5 9 may be not better but fine. You can play vstaff team without new_owo but how to play crune teams without crune?

**Comment by Pride1989** [comment]
there is no compulsion to run crune. If it is OP, it shall be **nerfed** not deleted.

**Comment by CleanLove2013** [comment]
> 

Shield and staff are not op but are important in battle system. Nerf them has no meaning to people have not them. Or all players have or no one has. Also, crune is too op

**Comment by CleanLove2013** [comment]
> there is no compulsion to run crune. If it is OP, it shall be **nerfed** not deleted.

Shield and staff are not op but are important in battle system. Nerf them has no meaning to people have not them. Or all players have or no one has. Also, crune is too op

**Pull request closed without merging**
