### PR TITLE
Quality of Life Changes

### PR DESCRIPTION
**Pull request by sfk-steelsong**
Had some time, roughed in some commonly mentioned QOL changes:

- upgrade trait with all available essence instead of typing out the number; `owo upg radar all`
- use multiple gems at the same time; `owo use 57 71 78` uses all 3 gems (or returns appropriate error messages)
- equip / use as an alias for weapon; `owo equip 2cfat snail` (if it gets non id args it sends them over to weapons to handle)

Also fixed the issue where the guild link in `owo rules` was the old dead one.

### CODE REVIEW

**Comment by poop-creator** [comment]
Friendly reminder that if this equip fix is commited, then it can also be removed from the to-do list project 👍

**Comment by sfk-steelsong** [comment]
Added a quest lock / unlock feature - needs a new column on quest table.

`alter table quest add locked char(1) not null default 'N';`

**Comment by sfk-steelsong** [comment]
To support setting huntbot by duration I used the `parse-duration` package that I'm using for snailbot's moderation commands.  It's pretty neat, you can do stuff like `2.8d6.2h3.1m` and it'll parse it to hours no prob.

I just convert the duration to cowoncy by multiplying by efficiency and cost and keep the rest of the logic.

**Comment by sfk-steelsong** [comment]
Added support for link logs on friendly battles, also enhanced it a bit to support comma separated flags instead of just `-`.  so you can do `owob user lvl 50, logs link` or `owob user -lvl=50 -logs=link` whatever you want.  Debated supporting `link` as a standalone flag but since it's effectively a sub-flag (like level or display) I left it like this.

**Comment by ChristopherBThai** [comment]
Just for the future, each change should be its own PR.

**Pull request merged**
