### PR TITLE
Added weapon's shop ID when buying a weapon.

### PR DESCRIPTION
**Pull request by Caviarbro**
A nice little addition, mostly design-wise (also improves clarity when buying a weapon from the shop).

### CODE REVIEW

**Comment by Nikhil0108L** [comment]
@Caviarbro bro there is nothing changes then why this issue fix 🤔🤔🤔

**Comment by Caviarbro** [comment]
> @Caviarbro bro there is nothing changes then why this issue fix 🤔🤔🤔

This doesn't fix anything, it's only an enhancement.

**Comment by Nikhil0108L** [comment]
> > @Caviarbro bro there is nothing changes then why this issue fix 🤔🤔🤔
> 
> This doesn't fix anything, it's only an enhancement.

Then what you enhances there is nothing changes in owoshop w

**Comment by Caviarbro** [comment]
> > > @Caviarbro bro there is nothing changes then why this issue fix 🤔🤔🤔
> > 
> > 
> > This doesn't fix anything, it's only an enhancement.
> 
> Then what you enhances there is nothing changes in owoshop w

Seems like you don't understand how Pull Requests work, everyone can create them but the 'owner' needs to merge them to the source code for the changes to apply.

**Comment by Nikhil0108L** [comment]
> > > > @Caviarbro bro there is nothing changes then why this issue fix 🤔🤔🤔
> > > 
> > > 
> > > This doesn't fix anything, it's only an enhancement.
> > 
> > 
> > Then what you enhances there is nothing changes in owoshop w
> 
> Seems like you don't understand how Pull Requests work, everyone can create them but the 'owner' needs to merge them to the source code for the changes to apply.

Oo it's mean anyone can say owner to add this feature in pull request

**Pull request merged**
