### PR TITLE
Add owo top cash as a viable command

### PR DESCRIPTION
**Pull request by 7te**
I have been mindlessly trying to type owo top cash for several months without success, in myopinion, if owo cash exists then owo top cash should also exist.

### CODE REVIEW

**Comment by djradnad** [comment]
very much agree, `top pray` is another i do by accident when its `top luck` xd

**Comment by Byflos** [comment]
> I have been mindlessly trying to type owo top cash for several months without success, in myopinion, if owo cash exists then owo top cash should also exist.

Did you know that you can type owo top cowoncy and you will have what you looking? But agree, since cash is another way it should be add it just like top luck and top pray

**Comment by 7te** [comment]
> Did you know that you can type owo top cowoncy and you will have what you looking?

Yes, of course. I just use owo cash to check my money, and always try to check owo top cash before remembering it doesn't work. That's why I made the PR.

**Comment by Byflos** [comment]
> > Did you know that you can type owo top cowoncy and you will have what you looking?
> 
> Yes, of course. I just use owo cash to check my money, and always try to check owo top cash before remembering it doesn't work. That's why I made the PR.

Got you my friend, I support your request

**Pull request merged**
