### PR TITLE
Add Marriage Leaderboard

### PR DESCRIPTION
**Pull request by Togira123**
This pull request adds a marriage leaderboard ordered by days collected dailies together. The "me" leaderboard still needs the correct queries, I was a little bit confused when I tried to figure it out, @ChristopherBThai I hope you can add those and then I'd be ready for merge

### CODE REVIEW

**Comment by Togira123** [comment]
ah yes and I formatted the code and improved the display function too :D

**Comment by Togira123** [comment]
I added the correct queries, please still test them before actually merging this but it should work :D

**Comment by ChristopherBThai** [comment]
Please run `npm run format`

**Comment by Togira123** [comment]
done!

**Pull request closed without merging**
